//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dc4w.rc
//
#define ID_BROWSE1                      3
#define ID_BTN_COMPARE                  3
#define ID_BROWSE2                      4
#define ID_BTN_EXPANDED                 4
#define ID_BTN_OUTLINE                  5
#define IDS_STRING51                    51
#define IDS_STRING52                    52
#define IDS_STRING53                    53
#define IDS_STRING54                    54
#define IDS_STRING55                    55
#define IDS_STRING56                    56
#define IDS_STRING57                    57
#define IDI_ICON1                       101
#define IDR_MENU1                       102
#define IDD_DLGABOUT                    103
#define IDR_ACCELERATOR1                104
#define IDD_DIRECTORY                   105
#define IDD_SAVELIST                    106
#define IDD_COPYFILES                   107
#define IDD_GABRTDLG                    108
#define IDD_STRINGINPUT                 109
#define IDC_CURSOR1                     110
#define IDC_CURSOR2                     111
#define IDD_DLG_DIFF                    112
#define IDD_SHOWCOPY                    113
#define IDD_HELPFIND                    114
#define IDD_DLG_EXCLUDE                 115
#define IDR_MENU2                       116
#define IDD_SAVEDIFF                    117
#define IDD_DIALOG1                     118
#define IDD_VERIFY_COPY                 118
#define IDB_BITMAP1                     119
#define IDD_PREFERENCES                 120
#define IDC_CURSOR3                     121
#define IDD_COMPARE                     122
#define IDD_OUTLINE                     123
#define IDD_EXPANDED                    124
#define IDD_PREFERENCE2                 126
#define IDD_PREFERENCE3                 127
#define IDD_COPYFILES2                  128
#define IDR_MAINMENU                    129
#define IDD_ZIPUP                       130
#define IDD_RENZIP                      131
#define IDD_DLG_EXCLUDE2                132
#define IDR_MNU_LISTVIEW                133
#define IDI_ICON2                       134
#define IDI_ICON3                       135
#define IDI_ICON4                       136
#define IDD_VERIFY_DELETE               137
#define IDC_EDIT1                       1000
#define IDD_LABEL                       1001
#define IDC_EDIT3                       1001
#define IDD_RECURSIVE                   1002
#define IDC_EDIT4                       1002
#define IDD_LAB1                        1003
#define IDC_EDIT5                       1003
#define IDD_DIR1                        1004
#define IDC_EDIT6                       1004
#define IDD_LAB2                        1005
#define IDC_EDIT7                       1005
#define IDD_DIR2                        1006
#define IDD_FILE                        1007
#define IDD_IDENTICAL                   1008
#define IDD_DIFFER                      1009
#define IDD_LEFT                        1010
#define IDD_RIGHT                       1011
#define IDD_FROMGROUP                   1012
#define IDD_FROMLEFT                    1013
#define IDD_FROMRIGHT                   1014
#define IDC_LPAGENR                     1015
#define IDD_VERSION                     1016
#define IDC_LABLEFT                     1017
#define IDC_LABRITE                     1018
#define IDC_LABIDENT                    1019
#define IDC_LABDIFF                     1020
#define IDC_LABUNK                      1021
#define IDC_LABCWD                      1022
#define IDC_LABUNK2                     1022
#define IDC_ED_CWD                      1023
#define IDC_BUT_SRCH                    1024
#define IDC_ED_SAVE                     1025
#define IDC_CHECK1                      1026
#define IDC_RADIO1                      1027
#define IDC_RADIO2                      1028
#define IDC_RADIO3                      1029
#define IDC_RADIO4                      1030
#define IDC_RADIO5                      1031
#define IDC_RADIO6                      1032
#define IDC_LAB_CWD                     1033
#define IDC_LAB_RT                      1034
#define IDC_LIST1                       1035
#define IDC_LAB_FROM                    1036
#define IDC_BUT_DELETE                  1037
#define IDC_BUT_RESTORE                 1038
#define IDC_LAB_TO                      1039
#define IDC_LAB_CMD                     1040
#define IDC_LAB_FULL                    1041
#define IDC_CH_SEL                      1042
#define IDC_CMPLEFT                     1043
#define IDC_BUTADD                      1044
#define IDC_CHECK8                      1045
#define IDC_CUR_SEL                     1046
#define IDC_MOVEDLEFT                   1047
#define IDC_MOVEDRIGHT                  1048
#define IDC_CHECK2                      1049
#define IDC_DIR1                        1050
#define IDC_DIR2                        1051
#define IDC_LAB1                        1052
#define IDC_LAB2                        1053
#define IDC_CHECK3                      1054
#define IDC_COMBO_FILE                  1055
#define IDC_COMBO_SAVE                  1056
#define IDC_LABWARN                     1057
#define IDC_CHECK4                      1058
#define IDC_BACKUP                      1059
#define IDC_CURMODE                     1060
#define IDC_COPYALL                     1061
#define IDC_ABORTALL                    1062
#define IDC_CHK_WARN                    1063
#define IDC_BUT_INVERT                  1064
#define IDC_INIFILE                     1065
#define IDC_LOGFILE                     1066
#define IDC_EXISTS                      1067
#define IDC_CMPRITE                     1069
#define IDC_CMPOF                       1070
#define IDC_TAB1                        1072
#define IDC_COMBO1                      1073
#define IDC_SHOWIDENT                   1074
#define IDC_NOCASE                      1075
#define IDC_LISTLABEL                   1076
#define IDC_AUTOSEL                     1077
#define IDC_SSTAB1                      1078
#define IDC_IGNORETERM                  1079
#define ID_BTN_APPLY                    1080
#define ID_BTN_HELP                     1081
#define IDC_AUTOSEL2                    1082
#define IDC_OKSTATUS                    1083
#define IDC_LABUPDATE                   1084
#define IDC_LABDEL2                     1085
#define IDC_LISTTOTAL                   1086
#define IDC_LISTTOTAL2                  1087
#define IDC_SKIPQTXT                    1089
#define IDC_SKIPCCOMM                   1090
#define IDC_IGNORESP                    1091
#define IDC_CHECK9                      1092
#define IDC_CHECK7                      1093
#define IDC_EDIT2                       1094
#define IDC_LABRITE2                    1095
#define IDC_LABDIFF4                    1096
#define IDC_LABDIFF3                    1097
#define IDC_LABLEFT2                    1098
#define IDC_LABDIFF2                    1099
#define IDC_LABIDENT2                   1100
#define IDD_DIFFER2                     1101
#define IDC_BUT_OPTS                    1102
#define IDC_EDSOURCE                    1103
#define IDC_CHECK5                      1104
#define IDC_CHECK6                      1105
#define IDC_LIST3                       1107
#define IDC_LAB_EXCLUDE                 1108
#define IDC_BUTZIPIT                    1109
#define IDC_ZIP1                        1110
#define IDC_ZIP2                        1111
#define IDC_ZIP3                        1112
#define IDC_ZIP4                        1113
#define IDC_ZIP5                        1114
#define IDC_CURR_ZIP                    1114
#define IDC_ZIP6                        1115
#define IDC_WARN_OVR                    1115
#define IDC_BUTTON1                     1116
#define IDC_DESTINATION                 1117
#define IDC_COMPILER                    1118
#define IDC_IGNORETIME                  1119
#define IDC_IGNORETIME2                 1120
#define IDM_SHOW                        40000
#define IDM_FILE                        40001
#define IDM_DIR                         40002
#define IDM_CLOSE                       40003
#define IDM_ABORT                       40004
#define IDM_SAVELIST                    40005
#define IDM_COPYFILES                   40006
#define IDM_PRINT                       40007
#define IDM_EXIT                        40008
#define IDM_EDITLEFT                    40009
#define IDM_EDITRIGHT                   40010
#define IDM_EDITCOMP                    40011
#define IDM_SETEDIT                     40012
#define IDM_OUTLINE                     40013
#define IDM_EXPAND                      40014
#define IDM_PICTURE                     40015
#define IDM_FPCHANGE                    40016
#define IDM_FCHANGE                     40017
#define IDM_LONLY                       40018
#define IDM_RONLY                       40019
#define IDM_BOTHFILES                   40020
#define IDM_LNRS                        40021
#define IDM_RNRS                        40022
#define IDM_NONRS                       40023
#define IDM_IGNBLANKS                   40024
#define IDM_INCSAME                     40025
#define IDM_INCLEFT                     40026
#define IDM_INCRIGHT                    40027
#define IDM_INCDIFFER                   40028
#define IDM_ABOUT                       40029
#define IDM_TIME                        40030
#define IDM_OPTEXACT                    40031
#define IDM_WRITEDIFF                   40032
#define IDM_RECURSIVE                   40033
#define IDM_OPTEXCLUDE                  40034
#define IDM_EDITEXCLUDE                 40035
#define IDM_VIEW_NEXT                   40036
#define IDM_WARNING                     40037
#define IDM_UPDFILE                     40038
#define IDM_SHOWTOOLTIP                 40039
#define IDM_REVERSE                     40040
#define IDM_REFRESH                     40041
#define IDM_DELETEFILE                  40042
#define IDM_UPDATE                      40043
#define IDM_NEWER                       40044
#define IDM_OLDER                       40045
#define IDM_DIFFALL                     40046
#define IDM_ADDSTATUS                   40047
#define IDM_PREFERENCES                 40048
#define IDM_NEXTINLIST                  40049
#define IDM_FILECOPY                    40050
#define IDM_SHOWCOPY                    40051
#define IDM_SHOWSAME                    40052
#define IDM_SHOWMOVE                    40053
#define IDM_SHOWTAG                     40054
#define IDM_EDITCOPY                    40055
#define IDM_OPTIGNOREDT                 40056
#define IDM_OPTADDROW                   40057
#define IDM_CLEARVIEWED                 40058
#define IDM_USEEXCLUDE                  40059
#define IDM_ENABLEDELETE                40060
#define IDM_DELETEONE                   40061
#define IDM_IGNOREEOL                   40062
#define IDM_IGNCASE                     40063
#define IDM_EDITZIPUP                   40064
#define IDM_FILE_RENZIP                 40065
#define IDM_OPTALTDISPLAY               40066
#define IDM_REPORT                      40067
#define IDM_LIST                        40068
#define IDM_LARGEICONS                  40069
#define IDM_SMALLICONS                  40070
#define IDM_LISTVIEWOFF                 40071
#define IDM_LISTVIEW50                  40072
#define IDM_LISTVIEW100                 40073
#define IDM_HOVERSEL                    40074
#define IDM_LVADDGRID                   40075
#define IDM_EXCLUDE                     40076
#define ID_VIEW_NOEXCLUDES              40078
#define ID_FILELISTOPTIONS_FULLPATHNAME 40079
#define ID_FILELISTOPTIONS_RELATIVENAME 40080
#define ID_FILELISTOPTIONS_FILETITLEONLY 40081
#define ID_FILE_CREATEZIPFILE           40082
#define ID_HELP_BRIEFHELP               40083
#define IDM_DELETELEFTFILE              40084
#define IDM_EXCLUDEREPOS                40089

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40090
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
